### ISSUE TITLE
Relocated plugins path is not included in installation RPATH

### ISSUE THREAD

**Issue by jnbrunet** [sofa-framework/sofa#1395]
When doing `make install`, the RPATH of the libraries is set to "../lib:$ORIGIN/../lib:$$ORIGIN/../lib", and  does not include the path to its relocated dependencies:

```
$ ./bin/runSofa
./runSofa: error while loading shared libraries: libSofaValidation.so.1.0: cannot open shared object file: No such file or directory
```

```
$ find . -name libSofaValidation.so.1.0
./plugins/SofaValidation/lib/libSofaValidation.so.1.0
```

Same thing happen if we link our project to some of SOFA's core library:
```
$ lddtree my_plugin.so
my_plugin.so
    libSofaMisc.so.20.06.99 => /sofa/build/install/lib/../lib/libSofaMisc.so.20.06.99
        libSofaMiscEngine.so.20.06.99 => /sofa/build/install/lib/../lib/../lib/libSofaMiscEngine.so.20.06.99
            libSofaNonUniformFem.so.1.0 => not found
```
and again.
```
$ find . -name libSofaNonUniformFem.so.1.0
./plugins/SofaNonUniformFem/lib/libSofaNonUniformFem.so.1.0
```

______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
Because both SofaValidation and SofaNonUniformFem can't be plugins (aka. "relocatable") if we want them to be hard-linked to something. Plugins are supposed to be loaded/unloaded dynamically at run time through the PluginManager (which is already capable of parsing the plugins directory). 

So we have to choose:
1. SofaValidation and SofaNonUniformFem are plugins, we want to be able to load/unload them with PluginManager --> runSofa has to use PluginManager to load them.
2. SofaValidation and SofaNonUniformFem are not plugins, they are libs potentially hard-linked to runSofa (or any other part of SOFA) and thus must stay in "lib" (in "bin" on Windows) --> we have to remove their "relocatable" attribute in CMakeLists.

Personally, I already chose solution 2 in my current CMake branch (wip).

**Comment by jnbrunet** [comment]
Hey @guparan ,

Sorry for the late response, I'm having a slow week.

Yeah I agree with your solution 2, if SofaValidation and SofaNonUniformFem are hard dependencies of core libraries, they becomes almost "core" libraries themselves and should be in "lib" ("bin" on Windows). 

Will this be in your big cmake refactoring branch (aka #1397)?

**Comment by guparan** [comment]
Yes it is :+1:
