### ISSUE TITLE
[CI] print call stack when a test crashes

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#149]
Would it be possible to print the call stack in the console when a gtest crashes?
An xml file is generated, but it is complicated to access it, its content could be printed directly in the console. The resulting raw output would be huge but at least we would have access to useful informations.

**Comment by damienmarchal** [comment]
+1. 

We probably simply need to install the autodump trick somewhere in Sofa_test.

**Comment by guparan** [comment]
I just spent a significant amount of time to understand how we play with GTest and XML outputs in SOFA.
Printing a call stack should be done with #191 + #195. 
But there is still a problem in our way to report unit tests.
Currently what we do is to run all our tests with `--gtests_output:xml`. This is OK but sometimes we have crashes (often due to segfaults) in our tests. When a test crashes, it just stops. All the other steps/functions/cases are skipped and the XML output is not created.
So currently, for each crash, we are losing results.

This brings me a question: should we (1) handle the lost tests for each crash or (2) change the way we use GTest and detect crashes as failures? Is (2) even possible with segfaults?

**Comment by damienmarchal** [comment]
Seems done...so I close it.
