### ISSUE TITLE
runSofa_d.exe in Debug on Windows crash at start in CImg

### ISSUE THREAD

**Issue by epernod** [sofa-framework/sofa#1851]
Crash at
```
      // Allocate Memory for Image Read
      png_bytep *const imgData = new png_bytep[H];
      for (unsigned int row = 0; row<H; ++row) imgData[row] = new png_byte[(size_t)byte_depth*4*W];
      png_read_image(png_ptr,imgData);
      png_read_end(png_ptr,end_info);
```

I suspect the new background image...

**Comment by fredroy** [comment]
The new logo(s) are bitmaps (.bmp) so I dont think it would crash in libpng.... Or something is really wrong 🤐

**Comment by epernod** [comment]
ok after quick investigation the problem is that on windows: CImgPlugin_d.dll link with libpng16.dll instead of libpng16d.dll

**Comment by Camille-K** [comment]
I encountered a problem which I think is related: on my setup (Windows, debug) runSofa_d.exe crashes because it expects to find zlibd.dll, and only finds zlib.dll in build/bin/Debug. I manually copied zlibd.dll to try a quick fix, but then CImgPlugin could not load. Going to see it's dependencies, it seems to link with the non debug version zlib (which I had replaced), instead of zlibd, in the same way as it does for libpng16.
Trying to investigate, I found in the CImgPlugin CMakeLists.txt  two lines (74-75) which could explain this :
```
# Always link dependency targets in Release to avoid a Zlib debug/release mix.
# Because tiff needs zlib and tiff is only in Release in WinDepPack.
sofa_set_targets_release_only(${DEP_TARGETS})
target_link_libraries(${PROJECT_NAME} PUBLIC ${DEP_TARGETS})
```
If someone can check, I'm not entirely sure it is the same issue though
