### ISSUE TITLE
Implicit solvers must read the result of Mass::isDiagonal to speed up computations in case mass is diagonal

### ISSUE THREAD

**Issue by alxbilger** [sofa-framework/sofa#1923]
Implicit solvers can be optimized to compute faster if the mass matrix is diagonal. Currently this information is not used, whereas it is known by the mass component. Implicit solvers must be adapted and have a special branch for diagonal matrix for faster computation.

See https://github.com/sofa-framework/sofa/pull/1903

**Comment by alxbilger** [comment]
@jnbrunet How implicit solvers could take advantage of a diagonal mass matrix? There is already the function `addMDx` which depends on how the mass is stored. For example, it multiply dx by a single value in UniformMass, instead of multiplying by a matrix. What more can we do in implicit solvers?

**Comment by jnbrunet** [comment]
Hey @alxbilger,

I'll describe here the different steps of the solving process for a dynamic solver. Hopefully this could be useful at some point.

I have described this further in the documentation of Caribou's backward Euler solver [here](https://caribou.jnbrunet.com/classSofaCaribou_1_1ode_1_1BackwardEulerODESolver.html).

The last two equations are the one that will be fully assembled, given any solver other than the SOFA's [un-preconditioned] conjugate gradient (this one doesn't assemble any matrices).

We can simplify them for the case of only one Newton iteration, which is the same as the SOFA's EulerImplicit component:

```
[(1+h r_m)M + hB + h(h+r_k)K] da = [r_mM + B + r_k K] v + [F - T]
              (1)                          (2)               (3)
```
where `h = dt`, `F` is the internal force vector computed by the elastic forcefields, and `T` is the external force vector computed by pressure fields, gravitational fields, collisions, etc.

Here is what happens during the solve:

    (1) A = [(1+h r_m)M + hB + h(h+r_k)K]

    Building step:
        Here we go down on the current context sub-graph and call :
            1. `ff->addKToMatrix(&A)` and `f->addBToMatrix(&A)` for every force field "ff" found.
            2. `pc->applyConstraint(&A)` for every BaseProjectiveConstraintSet "pc" found. This will set to 0 lines and columns of fixed constraints.
        If a mechanical mapping "m" is found during the traversal, and m->areMatricesMapped() is false, the traversal stops before entering the subgraph of the mapping.

    Mechanical mappings step:
        In case we have mapped matrices, which is, system matrix of a slave mechanical object, accumulate its contribution to the global system matrix with:
          [A]ij += Jt * [A']ij * J
        where `A` is the master mechanical object's matrix (top level), `A'` is the slave mechanical object matrix (linked to the top level MO using a mapping) and `J=m.getJ()`
        is the mapping relation between the slave and its master.


    (2) [r_m M + B + r_k K] v
        Go down in the current context tree calling `addMBKdx` on every force field components, then go up from the leaves calling `applyJT` on every mechanical mappings. If the k mechanical parameter is not zero, the `applyDJT` will also be applied.
        NOTE: This correspond to the force terms dependent on the velocity, i.e. the damping terms : 
            [- r_m M  - B  +  r_k K] v
        where K is in fact -K by SOFA's convention, hence the positive (+) sign.

    (3)  [F - T]
        Go down in the current context tree calling `addForce` on every force field components, then go up from the leaves calling `applyJT` on every mechanical mappings.
        NOTE: This correspond to the force terms dependent on the displacement, i.e. :
            (-Ku + T)

Now, the damping and stiffness matrices `B` and `K` are usually sparse. Knowing in advanced that `M` is also sparse (or even diagonal), I would bet that we could optimize these operations `(aM + b B + c K) v`. This is even more important for non-linear systems since a third term of the type `(aM + bB + cK) a` appears and must be computed multiples times per time steps. 

Let me know if something is not clear, this part is very un-intuitive and I spent the past 2 weeks trying to understand it to implement non-linear dynamic solvers so it is fresh in my memory !

**Comment by alxbilger** [comment]
After a discussion with @jnbrunet, we have decided to close this issue as we think the current implementation cannot be optimized further.
However, we think it is useful to know if the diagonal mass is diagonal in case the system matrix is built (it's not the case in Sofa).
