### ISSUE TITLE
[SofaPython] reload imported modules

### ISSUE THREAD

**Issue by matthieu-nesme** [sofa-framework/sofa#193]
When an imported module is modified, the sofa app needs to be closed and launched again so the sofa-python interpreter integrates the modifications.
How to force reloading imported modules so any modification can be integrated when reloading the scene?
(right now, the reload works for modified main scene file, but is always using the original module code)

**Comment by damienmarchal** [comment]
Hi matt,

This is a good question,

To implement what you want to do I can see several approaches like: 
- a) adding a component <DoOnChange filename='importedFile.py'> to the scene 
- b) adding a component <DoOnChange directoryname='myProjectsScripts'/> 
- c)  adding a python binding to the FileMonitor in order to files from the python side, with this at the beginning of each python imported file you could do something like: Sofa.FileMonitor.register(__FILENAME__) (I don't remember how to get the filename but there is).  
 - d) the last solution is probably in adding "automatically" kind of hook on import to register the imported files 

I can probably tests these things quickly and make you a report on that. 

But my first attempt would be to try the (c) solution. Because as it will be explicit it can be more easy to control undesirable... side effect (compared to (d)).

**Comment by damienmarchal** [comment]
Hi matt (again),

My first answer was in fact out of the topic (my answer was about livecoding that exhibit the same behavior but was not about the reload)  :) 

EDIT: my first attempt will probably to try to recreated a new python interpreter from scratch, otherwise there is very good support for that in python

**Comment by damienmarchal** [comment]
Hi matt,

I wanted to test a very basic approach based on completely reinitializing the Python environment 
you can have a look here: https://github.com/SofaDefrost/sofa/tree/reinit-plugin

But there is problem with numpy (an probably other modules) that does not support to be reloaded and crashing sofa. But if I comment the numpy parts it is working ok. 

Now the challenge is either to fix the numpy crash or to come with a different approach (probably closer to what I implemented in the livecoding module) in which we don't destroy the python environment but only reload some of the modules.

D

**Comment by matthieu-nesme** [comment]
I see, thanks to have a look at it.
Au secours encore un reinit! ;)

Could we find a way to clear/empty the python environment rather than deleting and creating a new one?

I guess the numpy problem comes from PythonEnvironment.cpp:70 ^^

**Comment by damienmarchal** [comment]
I actually just finished a much better version that is not deleting the environment anymore... please have a look.

EDIT: and it is not crashing with numpy. 
EDIT: Instead of using a per plugin reinit we could probably trigger the cleaning by calling the cleaning code when the scene is destructed.

**Comment by matthieu-nesme** [comment]
I will need some explanations on that version as it is above my python skills.

yes for EDIT2!

**Comment by damienmarchal** [comment]
@matthieu-nesme 

The version is very simple...
In the constructor we:
- record the already loaded modules, 
- install a hook on the import function. 

At each subsequent import we record in a second list the imported modules. 
Then when calling uninstall we remove from python module cache the one that are in this second list...(thus returning to the previous loading state)

This force python to reload them next time it sees an import.

About the re-init... 
Do you know how to be notified when the scene is going to be destructed and if there is no...is this something you could implement easily ? 

EDIT: I cleaned the branch for a PR once the reinit stuff cleared.

**Comment by damienmarchal** [comment]
Merge.
