### ISSUE TITLE
Bug with 2 SparseGridTopology in the same Node

### ISSUE THREAD

**Issue by epernod** [sofa-framework/sofa#1975]
```
    <MeshObjLoader name="loader1" filename="mesh/cylinder-1.obj" translation="0 2 0"/>
    <SparseGridTopology name="grid1" n="4 2 4" position="@loader1.position" drawHexahedra="1" />
    <OglModel name="Visual" src="@loader1" />
    
    <MeshObjLoader name="loader2" filename="mesh/cylinder-1.obj" translation="0 0 0"/>
    <SparseGridTopology name="grid2" n="4 2 4" position="@loader2.position" drawHexahedra="1" />
    <OglModel name="Visual" src="@loader2" />
```

the second grid is totally wrong in this example....

![image](https://user-images.githubusercontent.com/21199245/113331469-4e7d4080-9320-11eb-86b1-2a4e8c7ce0f8.png)

**Comment by fredroy** [comment]
In my opinion, all *GridTopology should be removed, and replaced with an engine computing a grid and then set into a Topology.
In this case, the bug comes from the facts that the "position" field (a Data called seqPoints in the code) is used both as input and output. So I strongly suspect that the update mechanism is overwritting the values.

If you remove the oglmodel (and add the facets...), it works.

```xml
    <MeshObjLoader name="loader1" filename="mesh/cylinder-1.obj" translation="0 2 0"/>
    <SparseGridTopology name="grid1" n="4 2 4" src="@loader1" drawHexahedra="1" />
    
    <MeshObjLoader name="loader2" filename="mesh/cylinder-1.obj" translation="0 0 0"/>
    <SparseGridTopology name="grid2" n="4 2 4" src="@loader2" drawHexahedra="1" />
``` 
 <img src="https://user-images.githubusercontent.com/11028016/114160763-90614480-9927-11eb-9ba8-4961a83a5fac.png" width="300" >
