### ISSUE TITLE
Invalid literal suffix

### ISSUE THREAD

**Issue by flm8620** [sofa-framework/sofa#323]
[Here](https://github.com/sofa-framework/sofa/blob/33690ee02117a875f4332996932a327736d6d7ea/applications/projects/runSofa/Main.cpp#L323)

The single quote mark is LEFT SINGLE QUOTATION MARK U+2018, which causes error in my compiler(VS2015). 
It's better to use APOSTROPHE U+0027

Error:
```
73>sofa\sofa\v16.12\src\applications\projects\runSofa\Main.cpp(316): error C3688: invalid literal suffix '鈥for'; literal operator or literal operator template 'operator ""鈥for' not found
73>sofa\sofa\v16.12\src\applications\projects\runSofa\Main.cpp(316): error C2146: syntax error: missing ';' before identifier '鈥'
73>sofa\sofa\v16.12\src\applications\projects\runSofa\Main.cpp(316): error C2065: '鈥': undeclared identifier
73>sofa\sofa\v16.12\src\applications\projects\runSofa\Main.cpp(316): error C2065: 'formatting鈥': undeclared identifier
```

**Comment by damienmarchal** [comment]
Hello @flm8620 

It is very interesting, I didn't even knew that stuff in a pair of " " could cause compilation problem. 
I'm also surprised that our Continuous integration system is compiling sofa with VS2015 but didn't reported a problem. Maybe something related with the language you use on your system ? 

Anyway, thank you very much for your report. If you have time maybe you can submit a pull-request to fix that otherwise I will do it. 

Regards,

**Comment by maxime-tournier** [comment]
The string should be properly prefixed as per the standard: http://en.cppreference.com/w/cpp/language/string_literal

**Comment by flm8620** [comment]
I know the reason. My OS is windows 8, language is French. But I have some softwares are set to Chinese. 
The UFT-8 code of LEFT SINGLE QUOTATION MARK is 0xE2 0x80 0x98.
The weird character 鈥 has code 0xE2 0x80 in GBK.
I have idea why Visual Studio use GBK instead of UTF-8.
