### ISSUE TITLE
Please carefully consider impact before moving files around (i.e. discussion on the current plugin / NG PRs)

### ISSUE THREAD

**Issue by JeremieA** [sofa-framework/sofa#482]
Hello,

I saw that several PRs are in work that move potentially lots of source files into plugins (#396, #407, #408, #477).
These types of changes can be very painful for everyone looking at file histories and/or not working exclusively on master:
 - all existing branches / PRs are very likely to cause conflict. Yes git does its best to try to match files in different paths but this is not reliable at all. Example issues: it won't move files that are created in the same directories in other branches/PRs, you have to be expert in all the rename match heuristics within git in order to be able to use merge with 10s of commits with mismatching file hierarchies (and there is none that I know of that will work well enough to be always used)
 - the history of all affected files will be polluted by this move. Example: it is tricky to know the history of all the SofaKernel files before May 2016 [(example)](https://github.com/sofa-framework/sofa/commits/master/SofaKernel/framework/sofa/core/BaseState.h) (can someone remind me what we gained by this massive move? I would like to know because that's the number-one time-waster on our end for merges/history tracking)

So I would like to know if those considerations were understood before doing this once again ?

And as a counter-proposal, for discussion, that you are free to ignore, I would suggest a 3 steps approach :

1. First only change the CMake scripts / per-lib main header/cpp to convert them to plugins WITHOUT moving the actual source files
2. Document the proposed new directory hierarchy, propose it and wait for feedback from enough community members
3. Once there is an agreement on the hierarchy, apply it via a commit that does not change anything else (changes in cmake scripts should be done as a separate commit, to ease solving later merge/conflict issues)

And regarding point 2, instead of moving everything in `applications/plugins` that is only there because of a bad decision 10 years ago (it was simpler as we had to release the main directories as separate archives for licensing reason so we packed the couple of plugins we had together with the executables), I would propose to use the following:
 - _Sofa root directory_
   - SofaPlugins
     - SofaMiscForceField
     _..._
   - SofaPluginsDeprecated
     - SofaVRPNClient _any plugin we no longer support but still keep around if someone else want to pick it up_
   - SofaPluginsGPL
     - SceneCreator
     - SofaPML
     ... _any plugins with a GPL licence_
   - SofaPlugins(.*) _any other licences or additional private ones in other repos_

Note: as an alternative, for the libs that are currently modules, instead of moving to a generic uninformative "SofaPlugins" directory, we could instead move them to the SofaGeneral/SofaAdvanced/SofaMisc directory that already exists and host their main cmake file.

4 advantages to this instead of everything is `applications/plugins`:
1. one less directory to browse to in order to get to the actual source files
2. it discourage any assumption that all plugins are/must be in the same directory
3. clear separation of the different licences, so that we can be sure that a LGPL-only app does not actually include GPL-licenced headers (because of the useful convention to include plugins/lib classes with `MyPlugin/MyClass.h`, all codes must be compiled with options to add to the compiler path the parent of a plugin directory, currently because it is the same parent as plugins with different licences it is difficult to be sure unwanted code is not included)
4. it fits with the way of organizing all codes around collections of libraries, which was the original intent behind Helper/Core/DefaultType within SofaFramework, Simulation* within SofaSimulation, Base* within SofaBase, ..., but which unfortunately was not agreed to with everyone so stuck in years-long discussions and is now broken by adding a "SofaKernel" level. As a reminder of the key points of this way of organizing codes, the idea was to make it consistent where the code/targets are found (always within a sub-subdirectory) while allowing to share common scripts/docs/packaging/... at the "collection" level instead of copy/pasted within each plugin/library.

2 disadvantages that I see:
1. it would be useful to also move the other plugins to this new hierarchy (so more files would need to be moved in the end), but this can be done later, plugin-by-plugin, depending on the main maintainers of each
2. we might get stuck in an endless debate/discussion again...

**Comment by damienmarchal** [comment]
Hello Jérémie,

Thank you for rising this issue and for making a proposition answering the questions asked in #346.

"These types of changes can be very painful for everyone looking at file histories and/or not working exclusively on master:"
You are totally correct.

"So I would like to know if those considerations were understood before doing this once again ?"
As you ask the question, yes, these considerations were understood and discussed. The problem we have is that when people taking part in discussions are sharing similar concern they can agree on changes that does not fit others needs. This is why we value and regularly ask your feedback (using @JeremieA or @fjourdes).

Since we are on github nothing have been ever merged without a minimal shared approval (and this is a keystone for me to contribute to Sofa). So on my side I see no problem in withdrawing or updating the changes made of this is too cumbersome for your workflow.

In our workflow we try to stay as close as possible to master and among all the problem we see in the current sofa code base (eg: no being able to deprecate things, too long compilation time because of code coupling, in-coherent and hard to understand file scheme organization) keeping a traceable file history, despite important, was set to a low priority.

"And as a counter-proposal, for discussion, that you are free to ignore, I would suggest a 3 steps approach :"
Impossible, I'm totally opposed to ignoring people contributions (as I'm oposed about endless discussion :)). 
Step 1 and 2 actually fit our needs so we can do that (and actually contribute by PR to make this happens)...

About step 3...I have a:
- rather positive opinion on having a SofaPlugin/SofaPluginDeprecated
- moderated opinion on SofaPluginGPL
- negative opinion about using  SofaGeneral/SofaAdvanced/SofaMisc because it is extremely confusing. To explaine why...I bet a coffee that, if we take 100 sofa components and ask 10 developers where the component should be we will end up with totally different results (because what is advanced for someone is basic to another) so I fear that opening this kind of categorization is the root of endless discussion).


Damien.
