### ISSUE TITLE
Dashboard improvement

### ISSUE THREAD

**Issue by damienmarchal** [sofa-framework/sofa#52]
Hi,

The current dash board does not allows to differentiate tests that fails because they are 'showing'  a not yet fixed sofa defect to the one caused by regression (ie tests that were supposed  to work but don't anymore). 

This is a problem because while introducing new regression failure is a bad thing, introducing new tests that exhibit sofa defect is a positive thing. But they have the same results...turning the dashboard to orange.  

I see two consequences:
     - when there is test failures because of open-issues we will detect much less easily the regressions tests (that are 'more' important !)  
     - people will prevent themselves to push open-issues test to avoid to turn the dash board to a not green status (because they are ashamed...or because they prefer to preserve the readability of the dash board to detect regression)

So would it be possible to change that so that each tests with a pattern (lke "OpenIssue" in their name are counted separately  ?

This would allow to reports two numbers instead of one eg:
     regression test failure : 0 
     open issues tests failure: 123   
And also to let the dashboard green for open issues tests failure. 

DM.

**Comment by guparan** [comment]
Hi Damien,

Actually, Jenkins is already doing this, here is a regression: https://ci.inria.fr/sofa-ci/job/ubuntu_gcc-4.8_options/3955/testReport/(root)/ImagePNG_test/ImagePNG_NoFile/

We can also access this results with a GET request: https://ci.inria.fr/sofa-ci/job/ubuntu_gcc-4.8_options/3955/testReport/api/json?pretty=true
Just search for "REGRESSION".

So it is possible to count them in the "post build" step :)

About colors, I don't agree with you because it would make people think "It's green, I don't care about new tests failing". If we are adding (failing) tests, it is precisely because we want to warn people that something is broken and needs to be fixed.

**Comment by damienmarchal** [comment]
Hi guillaume, 

Many thanks for the links to the jenkins API, this will helps us in differentiating the tests. 

I think the meaning of the colors depend on what the dash board is used for:
  a) if the dash board is used to know what is the current state of the sofa code base (so answer the question: "is this version of sofa good") then, as you say, it should be red showing that something is bad. 

  b) but, if the dash board is used to get feedback of a given (personal) contribution (answering the question: "did I introduced regression or is my contribution positive"). In this perspective a transition from green-to-red will be considered as:
- "SHIT, I did something wrong !"
- "OMG, other people will see that !"
- "I quickly need to revert or fix that mess". 
- "But I have no time to fix the Sofa bug...so I remove the test i made showing an existing defect"  

From what I see in the defrost team the dash board is only use in the (b) situation and I regularly see people not commiting because they are afraid of putting the dash board to red.  

Consequently and if we want to increase the number of commits (containing tests showing existing sofa defect) we should reward contributor with an positive feedback mecanism (whatever it is).

DM.

**Comment by bcarrez** [comment]
I see the difference of point of view between you.

Guillaume wants the dashboard to show the absolute current state of Sofa, with all failing tests marking the commits as "broken/need to be fixed"
Damien sees more the average Sofa contributor point of view: "did I break something?"/"is Sofa better or worse with my last commit"

**_Would it be acceptable**_ to add a simple checkbox on the dashboard, to filter the *_OpenIssue tests ? This way, open issues don't polute the workflow of people not concerned/competent with them. 
By default this option would be disabled.

The same for pull request, new failing tests (marked as _OpenIssue) should not be marked as failures during the pull request, since they do not introduce new malfunctions but only reveal them, which is (in my opinion) a step toward the good direction, ie kind of an improvement ?

Once fixed, *_OpenIssue tests should be renamed and kept in the tests base as normal regression tests.

**Comment by damienmarchal** [comment]
I think that the proposal of bcarrez is a good one.

**Comment by damienmarchal** [comment]
No implemented..but let's close the issue for the moment.
