### ISSUE TITLE
[runsofa] -a -n conflict for batch

### ISSUE THREAD

**Issue by ErwanDouaille** [sofa-framework/sofa#552]
When you run -g batch (the batch version) the -n iteration is set to the default value and stop at 1000 (default value).

But in some case you might want to run a scene in batch mode until your scene stop or crash by itself. Then you try to use -a instead of -n. But -n is used by default in batch view.

______________________________________________________

Suggested labels:

**Comment by abhikrsagar** [comment]
If I understood the issue correctly, so we want to avoid conflict of -a and -n for batch version. For this we can prioritize -a  over -n in batch mode i.e. if -g and -a are encountered then override the default -n otherwise -n will suffice.

**Comment by ErwanDouaille** [comment]
Exactly, this is simple but it need to be discussed :)

**Comment by abhikrsagar** [comment]
Awesome so how to proceed on this. Shall I make a PR?

**Comment by ErwanDouaille** [comment]
Yes. Create a PR. Each Wednesday morning the dev team will review PR and decide if it can be merge or not. 

The file to modify for this issue is named batchGUI

**Comment by abhikrsagar** [comment]
Awesome. I will create a PR.

**Comment by m4n4n** [comment]
@ErwanDouaille 
How do I determine that the end point of the scene. As in the terminating condition of the iteration loop (which I guess will go on for infinite times)

**Comment by damienmarchal** [comment]
@ErwanDouaille I quickly looked at -a and -n and found no conflict.

Here is my understanding: 
'-a' is a boolean to start the simulation it says nothing about how long you want the simulation to run. 
'-n' set the number of timestemp to simulate. 

When in batch mode the '-a' option is implicitely to "true" (so adding it should change nothing).
While without '-n' the number of steps is set to the default value of 1000. 

If I understand you correctly what you want to do is to be able to loop "infinitely"  and not for a predefined amount of steps. So the problem is more in the default value of 1000 to me. If this is what you want I see several way to fix that:

- when -a is set and the -n options is not set then loop infinitely (I'm not a big fan of this one because it change the meaning of -a) 
- set the default duration to -n to a very big number so that it loop endlessly (I'm not a big fan because it change an existing default behavior that may be used by people in their script)
- change the -n option so that the user can either choose type something like -n infinite  as well as -n 10 

Any other suggestions ?

**Comment by ErwanDouaille** [comment]
The latest suggestion sounds good to me.
Why -a is true as default value for the bash mode ? Anyway, if the users are used to not define -a with the batch mode ...

**Comment by damienmarchal** [comment]
-a is true...probably because in batch mode it was not expected to have an user clicking on a button to start the scene :)

**Comment by ErwanDouaille** [comment]
Sure, but since it's the default behavior for other gui, it shouldn't be true for batch :p

Of course it's easier to define it as true by default ;)

Isn't it the case for qtview ? I remember seen something weird with the animation button changing the default value ...

**Comment by m4n4n** [comment]
@damienmarchal I was working on it and was successfully able to run infinite iterations with the command: bin/runSofa -g batch -n -1. 
One of the important changes this method required was changing unsigned nbIterations to signed nbIterations.
Should I go ahead and make a PR?

**Comment by damienmarchal** [comment]
Feel free to make PR when you think it is ready for you because this is the best way to get feedback.
