### ISSUE TITLE
windows 10 many files not found

### ISSUE THREAD

**Issue by ErwanDouaille** [sofa-framework/sofa#561]
When building runsofa (master version 16/01/18) it crash at runtime.

> [INFO]    [runSofa] No plugin will be automatically loaded
> - No custom list found at C:\sofaBuild\bin/bin/plugin_list.conf
> - No default list found at C:\sofaBuild\bin/bin/plugin_list.conf.default
> The constructor with a QGLFormat is deprecated, use the regular contructor instead.
> [ERROR]   [FileRepository] File icons/back.png NOT FOUND in :C:\sofaBuild\bin/share/sofa/gui/runSofa/resources/:C:\sofaBuild\bin/share/sofa/gui/qt/resources/
> [ERROR]   [FileRepository] File icons/home.png NOT FOUND in :C:\sofaBuild\bin/share/sofa/gui/runSofa/resources/:C:\sofaBuild\bin/share/sofa/gui/qt/resources/
> [ERROR]   [BaseViewer] Could not create file 'C:/sofa/share/textures/SOFA_logo.bmp'
> Valid extensions: dds
> 
> [ERROR]   [Image] Could not load image with extension png. Valid extensions: dds
> [ERROR]   [OglModel(VisualBody)] couldn't create an image from file textures/snakeColorMap.png
> [ERROR]   [OglModel(VisualBody)] 1 textures couldn't be loaded
> [ERROR]   [FileRepository] File docs/runsofa.html NOT FOUND in :C:\sofaBuild\bin/share/sofa/gui/runSofa/resources/:C:\sofaBuild\bin/share/sofa/gui/qt/resources/
> [INFO]    [SceneChecker] The 'APIVersion' directive is missing in the current scene. Switching to the default APIVersion level '17.06'
> [INFO]    [SceneChecker] Validating node ''.
> Activate checkers:
> - SceneCheckAPIChange
> - SceneCheckDuplicatedName
> - SceneCheckMissingRequiredPlugin
> 
> [ERROR]   [FileSystem::listDirectory()] C:\sofaBuild\bin/bin: error 3: Le chemin dÆaccÞs spÚcifiÚ est introuvable.
> 
> [ERROR]   [FileSystem::listDirectory()] C:\sofaBuild\bin/bin: error 3: Le chemin dÆaccÞs spÚcifiÚ est introuvable.

Plus, I had many troubles compiling it. I have to uncheck PSL (require SofaPython), but when SofaPython is checked there is many link problems. Finally, I both unchecked them.

______________________________________________________

Suggested labels:

**Comment by guparan** [comment]
Hi @ErwanDouaille 
Where was created `plugin_list.conf.default`? In `C:\sofaBuild\bin/bin` or in `C:\sofaBuild\bin`?

**Comment by ErwanDouaille** [comment]
This bug may affect every windows VS builds.
@guparan we investigate and found than the problem come from visual studio build directory named Release/Debug. I´m testing my PR and see if everything works well.

I added some specific MSVC code inside the main CMakefile to enforce VS to not create release/debug directory.

**Comment by damienmarchal** [comment]
A  quick summary of this problem. 

1) There is multiple variation of this problem and It impact several people at Defrost.
But the underlying idea is that we are using the executatable location to deduce the plugin & data location (normally EXEC_LOC/../bin or EXEC_LOC/../share). The problem is that when building with recent VS, VS adds and extra directory (Release or Debug) so the "../" in  "../bin" is "not enough" to go to the sofa root install directory which result in searching for plugins in PATH/bin/bin instead of PATH/bin  and PATH/bin/share instead of  PATH/share

2) The problem is specific to people that are using Visual Studio build solution for their builds as VS adds Release/Debug subdirectory to the build directory. The problem was probably existing before but it was made very obvious since PR #518 & PR #502 as now we always use the relative location to the executable to find the files like plugins or resoures.

3) I assume that the problem was not visible in our CI because for windows builds we are using Ninja  with VC compiler; as we don't use a real VS solution the Release/Debug extra path were not added. 

4) Erwan is working on a fix, to force CMake not to emit the extra subdirectories when using VS solution,  it is currently in a private branch : )

@ErwanDouaille please complete the summary is needed.

**Comment by fjourdes** [comment]
Just my 2 cents: On windows platform would having the current directory instead of "../bin" resolve the issue ?  
As it was done in 15e6436ec82a2ef857a5a21e2194a55820c37526

**Comment by damienmarchal** [comment]
François is right but isn't doing this will only fix the find plugin problem... this can be problematic as there is other part of Sofa that are using the executable with relative path to locate resources directory (eg: GuiDataRepository).

**Comment by fjourdes** [comment]
Hmm I don't know the specifics, but usually config files used to initialise paths exist in two versions, one for the build tree, and one for the install tree. 
- On the build tree you can do pretty much what you want and use absolute paths.
- Only the install tree requires relative paths, so that it is portable.

So technically if you use configuration files for the lookup of the directories where the resources are located, it can be dealt by 
- having a config file for the build tree which points to the absolute location of these ressources, 
- for the install tree two options
  - no config file required provided you make sure the the install takes place in the expected relative paths location
  - another config file generated with relative paths from the install binary dir to the installed resources directory
